FROM node

WORKDIR /app

# Copy everything to ensure all workspaces and package.json files are present for npm install
COPY . .

# Install workspace dependencies with hoisting (--legacy-peer-deps might help)
RUN npm install

WORKDIR /app/templates/admin

EXPOSE 3002

CMD ["npm", "run", "dev"]
