FROM node

WORKDIR /app

# Copy everything to ensure all workspaces and package.json files are present for npm install
COPY . .

# Install workspace dependencies with hoisting
RUN npm install --legacy-peer-deps

WORKDIR /app/templates/client

EXPOSE 3003

CMD ["npm", "run", "dev"]
