FROM node:26

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY packages/ ./packages/
COPY plugins/ ./plugins/
COPY client-template/ ./client-template/

RUN npm install

WORKDIR /app/client-template

EXPOSE 3003

ENV PORT=3003
ENV HOSTNAME=0.0.0.0

CMD ["npm", "run", "dev"]
